export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format. */
  DateTime: any;
  /** The `Upload` scalar type represents a file upload. */
  Upload: any;
};

export type CreatePostInput = {
  /** Raw generated by Draft.js */
  draftRaw?: InputMaybe<Scalars['String']>;
  isFollowOnly?: InputMaybe<Scalars['Boolean']>;
  postParentId?: InputMaybe<Scalars['Int']>;
};

export type CreatePostMentionInput = {
  /** Example field (placeholder) */
  exampleField: Scalars['Int'];
};

export type CreatePostTagInput = {
  /** Example field (placeholder) */
  exampleField: Scalars['Int'];
};

export type CreateTagInput = {
  /** Example field (placeholder) */
  exampleField: Scalars['Int'];
};

export type CreateUserInput = {
  email: Scalars['String'];
  password: Scalars['String'];
  username: Scalars['String'];
};

export type FeedInput = {
  options?: InputMaybe<FeedOptions>;
  page?: InputMaybe<Scalars['Int']>;
  take?: InputMaybe<Scalars['Int']>;
};

export type FeedOptions = {
  excludeFollowing?: InputMaybe<Scalars['Boolean']>;
};

export type FeedOuput = {
  __typename?: 'FeedOuput';
  list: Array<Post>;
  total: Scalars['Int'];
};

export type FindAllPostInput = {
  options?: InputMaybe<FindAllPostOptions>;
  page?: InputMaybe<Scalars['Int']>;
  take?: InputMaybe<Scalars['Int']>;
};

export type FindAllPostOptions = {
  page?: InputMaybe<Scalars['Int']>;
};

export type FindAllPostOutput = {
  __typename?: 'FindAllPostOutput';
  list: Array<Post>;
  total: Scalars['Int'];
};

export type FindAllPostReportInput = {
  page?: InputMaybe<Scalars['Int']>;
  take?: InputMaybe<Scalars['Int']>;
};

export type FindAllPostReportOutput = {
  __typename?: 'FindAllPostReportOutput';
  list?: Maybe<Array<PostReport>>;
  total?: Maybe<Scalars['Int']>;
};

export type FindAllUserInput = {
  page?: InputMaybe<Scalars['Int']>;
  take?: InputMaybe<Scalars['Int']>;
};

export type FindAllUserOutput = {
  __typename?: 'FindAllUserOutput';
  total: Scalars['Int'];
  users: Array<User>;
};

export type FollowInput = {
  page?: InputMaybe<Scalars['Int']>;
  take?: InputMaybe<Scalars['Int']>;
};

export type FollowMutationOutput = {
  __typename?: 'FollowMutationOutput';
  follower: User;
  following: User;
};

export type FollowOutput = {
  __typename?: 'FollowOutput';
  list: Array<User>;
  total: Scalars['Int'];
};

export type GetPostReportsInput = {
  page?: InputMaybe<Scalars['Int']>;
  take?: InputMaybe<Scalars['Int']>;
};

export type GetPostReportsOutput = {
  __typename?: 'GetPostReportsOutput';
  list: Array<PostReport>;
  total: Scalars['Int'];
};

export type GetPostsInput = {
  options?: InputMaybe<GetPostsOptions>;
  page?: InputMaybe<Scalars['Int']>;
  take?: InputMaybe<Scalars['Int']>;
};

export type GetPostsOptions = {
  onlyWithMedia?: InputMaybe<Scalars['Boolean']>;
};

export type GetPostsOutput = {
  __typename?: 'GetPostsOutput';
  list: Array<Post>;
  total: Scalars['Int'];
};

export type GetSavedPostsOutput = {
  __typename?: 'GetSavedPostsOutput';
  list: Array<PostSave>;
  total: Scalars['Int'];
};

export type LikeMutationOutput = {
  __typename?: 'LikeMutationOutput';
  post: Post;
  user: User;
};

export type LoginInput = {
  email: Scalars['String'];
  password: Scalars['String'];
};

export type LoginOutput = {
  __typename?: 'LoginOutput';
  accessToken: Scalars['String'];
  user: User;
};

export type Mutation = {
  __typename?: 'Mutation';
  createPost: Post;
  createPostMention: PostMention;
  createPostTag: PostTag;
  createTag: Tag;
  createUser: LoginOutput;
  deletePost: Scalars['Int'];
  removeFollower: RemoveFollowerOutput;
  removePostMention: PostMention;
  removePostTag: PostTag;
  removeTag: Tag;
  reportPost: PostReport;
  toggleFollow: FollowMutationOutput;
  toggleLike: PostLike;
  toggleSavePost: PostSave;
  updatePost: Post;
  updatePostMention: PostMention;
  updatePostTag: PostTag;
  updateSelf: User;
  updateTag: Tag;
};


export type MutationCreatePostArgs = {
  input?: InputMaybe<CreatePostInput>;
  medias?: InputMaybe<Array<Scalars['Upload']>>;
};


export type MutationCreatePostMentionArgs = {
  createPostMentionInput: CreatePostMentionInput;
};


export type MutationCreatePostTagArgs = {
  createPostTagInput: CreatePostTagInput;
};


export type MutationCreateTagArgs = {
  createTagInput: CreateTagInput;
};


export type MutationCreateUserArgs = {
  input: CreateUserInput;
};


export type MutationDeletePostArgs = {
  postId?: InputMaybe<Scalars['Float']>;
};


export type MutationRemoveFollowerArgs = {
  followerId: Scalars['Int'];
};


export type MutationRemovePostMentionArgs = {
  id: Scalars['Int'];
};


export type MutationRemovePostTagArgs = {
  id: Scalars['Int'];
};


export type MutationRemoveTagArgs = {
  id: Scalars['Int'];
};


export type MutationReportPostArgs = {
  input: PostReportInput;
};


export type MutationToggleFollowArgs = {
  followingId: Scalars['Int'];
};


export type MutationToggleLikeArgs = {
  postId: Scalars['Float'];
};


export type MutationToggleSavePostArgs = {
  postId: Scalars['Int'];
};


export type MutationUpdatePostArgs = {
  input?: InputMaybe<UpdatePostInput>;
  medias?: InputMaybe<Array<Scalars['Upload']>>;
};


export type MutationUpdatePostMentionArgs = {
  updatePostMentionInput: UpdatePostMentionInput;
};


export type MutationUpdatePostTagArgs = {
  updatePostTagInput: UpdatePostTagInput;
};


export type MutationUpdateSelfArgs = {
  backgroundPictureFile?: InputMaybe<Scalars['Upload']>;
  profilePictureFile?: InputMaybe<Scalars['Upload']>;
  update?: InputMaybe<UpdateUserInput>;
};


export type MutationUpdateTagArgs = {
  updateTagInput: UpdateTagInput;
};

export type Post = {
  __typename?: 'Post';
  author: User;
  createdAt: Scalars['DateTime'];
  /** Raw generated by Draft.js */
  draftRaw?: Maybe<Scalars['String']>;
  id: Scalars['Int'];
  isFollowOnly?: Maybe<Scalars['Boolean']>;
  likes: PostLikeOutput;
  medias: Array<PostMedia>;
  parents: PostPaginationOuput;
  replies: PostPaginationOuput;
  reports: GetPostReportsOutput;
  user: User;
};


export type PostLikesArgs = {
  input?: InputMaybe<PostLikeInput>;
};


export type PostParentsArgs = {
  input?: InputMaybe<PostPaginationInput>;
};


export type PostRepliesArgs = {
  input?: InputMaybe<PostPaginationInput>;
};


export type PostReportsArgs = {
  input?: InputMaybe<GetPostReportsInput>;
};

export type PostLike = {
  __typename?: 'PostLike';
  createdAt: Scalars['DateTime'];
  post: Post;
  user: User;
};

export type PostLikeInput = {
  page?: InputMaybe<Scalars['Int']>;
  take?: InputMaybe<Scalars['Int']>;
};

export type PostLikeOutput = {
  __typename?: 'PostLikeOutput';
  list: Array<User>;
  total: Scalars['Int'];
};

export type PostMedia = {
  __typename?: 'PostMedia';
  id: Scalars['Int'];
  path: Scalars['String'];
  post: Post;
};

export type PostMention = {
  __typename?: 'PostMention';
  post: Post;
  user: User;
};

export type PostPaginationInput = {
  page?: InputMaybe<Scalars['Int']>;
  take?: InputMaybe<Scalars['Int']>;
};

export type PostPaginationOuput = {
  __typename?: 'PostPaginationOuput';
  list: Array<Post>;
  total: Scalars['Int'];
};

export type PostReport = {
  __typename?: 'PostReport';
  createdAt: Scalars['DateTime'];
  post: Post;
  reason: Scalars['String'];
  user: User;
};

export type PostReportInput = {
  postId: Scalars['Float'];
  reason: Scalars['String'];
};

export type PostSave = {
  __typename?: 'PostSave';
  createdAt: Scalars['DateTime'];
  post: Post;
  user: User;
};

export type PostTag = {
  __typename?: 'PostTag';
  post: Post;
  tag: Tag;
};

export type Profile = {
  __typename?: 'Profile';
  backroundPicture?: Maybe<Scalars['String']>;
  bio?: Maybe<Scalars['String']>;
  displayname?: Maybe<Scalars['String']>;
  id: Scalars['Int'];
  profilePicture?: Maybe<Scalars['String']>;
  user: User;
};

export type ProfileWithoutUser = {
  __typename?: 'ProfileWithoutUser';
  backroundPicture?: Maybe<Scalars['String']>;
  bio?: Maybe<Scalars['String']>;
  displayname?: Maybe<Scalars['String']>;
  id: Scalars['Int'];
  profilePicture?: Maybe<Scalars['String']>;
};

export type Query = {
  __typename?: 'Query';
  feed: FeedOuput;
  isFollow: Scalars['Boolean'];
  isLikedPost: Scalars['Boolean'];
  isSavedPost: Scalars['Boolean'];
  login: LoginOutput;
  me: User;
  post: Post;
  postMention: PostMention;
  postReport: FindAllPostReportOutput;
  postTag: PostTag;
  posts: FindAllPostOutput;
  rememberMe: LoginOutput;
  tag: Tag;
  user: User;
  users: FindAllUserOutput;
};


export type QueryFeedArgs = {
  input?: InputMaybe<FeedInput>;
};


export type QueryIsFollowArgs = {
  followerId: Scalars['Int'];
  followingId: Scalars['Int'];
};


export type QueryIsLikedPostArgs = {
  postId: Scalars['Int'];
};


export type QueryIsSavedPostArgs = {
  postId: Scalars['Int'];
};


export type QueryLoginArgs = {
  input: LoginInput;
};


export type QueryPostArgs = {
  postId: Scalars['Int'];
};


export type QueryPostMentionArgs = {
  id: Scalars['Int'];
};


export type QueryPostReportArgs = {
  input?: InputMaybe<FindAllPostReportInput>;
};


export type QueryPostTagArgs = {
  id: Scalars['Int'];
};


export type QueryPostsArgs = {
  input?: InputMaybe<FindAllPostInput>;
};


export type QueryTagArgs = {
  id: Scalars['Int'];
};


export type QueryUserArgs = {
  username: Scalars['String'];
};


export type QueryUsersArgs = {
  input?: InputMaybe<FindAllUserInput>;
};

export type RemoveFollowerOutput = {
  __typename?: 'RemoveFollowerOutput';
  userId: Scalars['Int'];
};

export type Role = {
  __typename?: 'Role';
  label: Scalars['String'];
  level: Scalars['Int'];
  users: User;
};

export type RoleWithoutUser = {
  __typename?: 'RoleWithoutUser';
  label: Scalars['String'];
  level: Scalars['Int'];
};

export type SubUpdateProfileInput = {
  backroundPicture?: InputMaybe<Scalars['String']>;
  bio?: InputMaybe<Scalars['String']>;
  displayname?: InputMaybe<Scalars['String']>;
  profilePicture?: InputMaybe<Scalars['String']>;
};

export type Subscription = {
  __typename?: 'Subscription';
  follow: FollowMutationOutput;
  reportPost: PostReport;
  toggle_like: LikeMutationOutput;
};

export type Tag = {
  __typename?: 'Tag';
  createdAt: Scalars['DateTime'];
  tag: Scalars['String'];
};

export type UpdatePostInput = {
  /** Raw generated by Draft.js */
  draftRaw?: InputMaybe<Scalars['String']>;
  id: Scalars['Int'];
  isFollowOnly?: InputMaybe<Scalars['Boolean']>;
  mediasRemovedIds?: InputMaybe<Array<Scalars['Int']>>;
};

export type UpdatePostMentionInput = {
  /** Example field (placeholder) */
  exampleField?: InputMaybe<Scalars['Int']>;
  id: Scalars['Int'];
};

export type UpdatePostTagInput = {
  /** Example field (placeholder) */
  exampleField?: InputMaybe<Scalars['Int']>;
  id: Scalars['Int'];
};

export type UpdateTagInput = {
  /** Example field (placeholder) */
  exampleField?: InputMaybe<Scalars['Int']>;
  id: Scalars['Int'];
};

export type UpdateUserInput = {
  email?: InputMaybe<Scalars['String']>;
  isFollow?: InputMaybe<Scalars['Boolean']>;
  profile?: InputMaybe<SubUpdateProfileInput>;
  username?: InputMaybe<Scalars['String']>;
};

export type User = {
  __typename?: 'User';
  createdAt: Scalars['DateTime'];
  email: Scalars['String'];
  followers: FollowOutput;
  followings: FollowOutput;
  id: Scalars['Int'];
  isFollow: Scalars['Boolean'];
  /** Get user post */
  posts: GetPostsOutput;
  /** Get user profile */
  profile: ProfileWithoutUser;
  roles: Array<RoleWithoutUser>;
  /** Get user post */
  savedPost: GetSavedPostsOutput;
  username: Scalars['String'];
};


export type UserFollowersArgs = {
  input?: InputMaybe<FollowInput>;
};


export type UserFollowingsArgs = {
  input?: InputMaybe<FollowInput>;
};


export type UserPostsArgs = {
  input?: InputMaybe<GetPostsInput>;
};


export type UserSavedPostArgs = {
  input?: InputMaybe<GetPostsInput>;
};
